spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/budgettracker?sslmode=disable
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  devtools:
    add-properties: false